### ISSUE TITLE
A couple errors you might want to fix

### ISSUE THREAD

**Issue by ulfaslak** [yigitatay/FontGenerator#1]
Hi Yigit,

I'd like to try this out, but in its current form it doesn't run. Inside *FontGenerator.py*, `logging` is not imported (easy fix), `logger` is not defined (easy fix), but then having fixed these I get the error:

`AttributeError: type object 'Ui_MainWindow' has no attribute 'openErrorWindow'`

Do you know why this is happening? I'm not spending more time debugging this right now, but let me know when it is fixed I'd like to play around with the GUI.

/U

**Comment by yigitatay** [comment]
Hi Ulf,

I don’t get that error when I run it, but there are definitely issues with the exception handling, so if you comment out everything from line 22 to 41, it should work (since there shouldn’t be any exceptions). Also, I recommend that you change parameter 2 and maybe 3 as well, because those seem to be essential for getting a result that makes sense currently. Let me know if it still doesn’t work, and I’ll try to fix it.

Yigit

**Comment by ulfaslak** [comment]
Erasing line 22 to (and including) 41 then gives me the error:

```
Traceback (most recent call last):
  File "FontGenerator.py", line 239, in <module>
    ui.setupUi(MainWindow)
  File "FontGenerator.py", line 215, in setupUi
    self.setupVAE()
  File "FontGenerator.py", line 61, in setupVAE
    self.model.load_weights(weights_path)
  File "/Users/ulfaslak/.local/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/ulfaslak/.local/lib/python3.7/site-packages/keras/engine/network.py", line 1221, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by yigitatay** [comment]
Do you have the allDataDecoder.h5 file in the same directory as FontGenerator.py?

**Comment by ulfaslak** [comment]
Yep, didn't change anything other than removing those lines. Can you clone fresh and run it as-is?

**Comment by yigitatay** [comment]
I cloned it and ran it again. As you said, I got an error as well. However, when I ran it using the version of the weights file (allDataDecoder.h5) on my computer, it works fine. I tried deleting and re-pushing that file, but when I clone and run again, it doesn't work. I think the problem might be that the file is >100MB, and I use git lfs to be able to push it, but that might be corrupting the file somehow. The only solution that I can think of now is to share the file with you through Drive, because I don't know another way to push large files on Github other than git lfs. I'll try to fix this. I'll send you the link through Canvas.
